Update README_ZH.md
OpenTenBase/OpenTenBase pull request #48
Opened 2024-01-18 10:30 UTC by jiengup

Add Chinese version of README.md
close #3

2024-01-18 10:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/OpenTenBase/OpenTenBase?pullRequest=48) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/OpenTenBase/OpenTenBase?pullRequest=48) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/OpenTenBase/OpenTenBase?pullRequest=48) it.</sub>

2024-01-19 02:44 UTC, bartdong requested changes
Thank you for contributing! Some points need to be optimized.
Line 14 needs to be optimized.
Line 67 missing one 'n' in 'bin'.
Line 155 should be "登录".
Line 159 and 162 `deploy all` and `init all` in the brackets no need to translate.
Line 22 and 181 the URL need to be changed according to README.MD's latest version.

2024-01-19 05:27 UTC, jiengup commented
@bartdong 
Thanks for your suggestion.
Sorry for my carelessness and all the requests are met.

2024-01-19 07:29 UTC, bartdong approved these changes
LGTM

2024-01-19 07:29 UTC, merged